### ISSUE TITLE
Invalid trajectory error when setting durations <1 s using the cartesian trajectory controller

### ISSUE THREAD

**Issue by tomse-h** [UniversalRobots/Universal_Robots_ROS_controllers_cartesian#12]
When I try to send a trajectory goal with the time_from_start parameter set to a value <1 s, the controller aborts indicating an invalid trajectory. Is there a lower bound for the movement duration?

**Comment by stefanscherzinger** [comment]
Hi @tomse-h 

> Is there a lower bound for the movement duration?

No, not really. But the [`time_from_start`](https://github.com/UniversalRobots/Universal_Robots_ROS_cartesian_control_msgs/blob/main/msg/CartesianTrajectoryPoint.msg#L1) durations of the waypoints must be strictly increasing. Note that the current robot state is implicitly prepended  as first waypoint with `time_from-start = 0` to the user-defined trajectory. If something converts your `<1` to an integer (`=0`), that would fail.

Could you `rostopic echo ` on the goal topic and post the output here?

**Comment by tomse-h** [comment]
Hi, thanks for the reply. It was indeed that case, that something in my program converted the duration to an integer and thus to 0.
