### ISSUE TITLE
Conflict with ros-melodic-cob-twist-controller

### ISSUE THREAD

**Issue by gavanderhoorn** [UniversalRobots/Universal_Robots_ROS_controllers_cartesian#9]
From ROS Answers:

> When i run sudo apt-get upgrade i receive following error:
> 
> > ```
> > Reading package lists... Done
> > Building dependency tree       
> > Reading state information... Done
> > You might want to run 'apt --fix-broken install' to correct these.
> > The following packages have unmet dependencies:
> >  ros-melodic-ros-controllers-cartesian : Depends: ros-melodic-twist-controller but it is not installed
> >  ros-melodic-twist-controller-dbgsym : Depends: ros-melodic-twist-controller (= 0.1.4-1bionic.20210921.212715) but it is not installed
> > E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
> > ```

This turned out to lead to:

> ```
> Unpacking ros-melodic-twist-controller (0.1.4-1bionic.20210921.212715) ...
> dpkg: error processing archive /var/cache/apt/archives/ros-melodic-twist-controller_0.1.4-1bionic.20210921.212715_amd64.deb (--unpack):
>  trying to overwrite '/opt/ros/melodic/lib/libtwist_controller.so', which is also in package ros-melodic-cob-twist-controller 0.8.12-1bionic.20210921.230048
> Errors were encountered while processing:
>  /var/cache/apt/archives/ros-melodic-twist-controller_0.1.4-1bionic.20210921.212715_amd64.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> ```

Seems the `twist_controller` target in this package (ie: `twist_controller`) clashes with an identically named library in `cob_twist_controller`.

**Comment by gavanderhoorn** [comment]
Post on ROS Answers: [ros-melodic-ros-controllers-cartesian : Depends: ros-melodic-twist-controller but it is not installed](https://answers.ros.org/question/389932).

**Comment by gavanderhoorn** [comment]
@fmessmer also FYI.

**Comment by urrsk** [comment]
@gavanderhoorn thanks for info

**Comment by gavanderhoorn** [comment]
I believe it would be good "ROS citizenship" to fix the problem here, in this repository/package, seeing as the `cob_twist_controller` has been around for a couple of years.

**Comment by fmauch** [comment]
I agree. I am currently drowning in work, but this seems something I'll have totry to squeeze in.

**Comment by stefanscherzinger** [comment]
@fmauch I could take care of this. If there are no particular preferences, I would suggest `cartesian_twist_controller`. Also to be more consistent with the other packages in this repo.

**Comment by fmauch** [comment]
That would be fine with me. Thank you Stefan.
